[book]
title = "todo"
language = "en"
src = "docs"

[output.html]
default-theme = "latte"
preferred-dark-theme = "mocha"
additional-css = ["theme/catppuccin.css", "theme/custom.css"]
site-url = "/rust-todo/"
